server:
  port: 8130

spring:
  application:
    name: service-oss
  profiles:
    active: dev

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: 你自己的id
    access-key-secret: 你自己的密钥
    bucket-name: srb-file-by-ks
