server:
  port: 8848
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core
  datasource:
    type: com.zaxxer.hikari.HikariDataSource  # 默认的, 可以不用设置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
mybatis-plus:
  # sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/ks/srb/core/mapper/xml/*.xml
logging:
  level:
    root: info

